name: Build Book with mdBook

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install mdbook
        run: cargo install mdbook

      - name: Build book
        run: mdbook build

      - name: Upload book output
        uses: actions/upload-artifact@v4
        with:
          name: book-output
          path: output/
